//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceScraper_HTMLAgilityPack
{
    using System;
    using System.Collections.Generic;
    
    public partial class NasdaqStock
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public string IndexValue { get; set; }
        public string Change { get; set; }
        public string NetPercent { get; set; }
        public string High { get; set; }
        public string Low { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
